version: '3.4'

networks:
  frontend:

services:
  crudtestDb:
    container_name: crudtest-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@1234#
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - frontend

  mc2.crudtest.presentation.server:
    image: ${DOCKER_REGISTRY-}mc2crudtestpresentationserver
    build:
      context: .
      dockerfile: Mc2.CrudTest.Presentation/Server/Dockerfile
    ports:
        - 9080:80
        - 9081:443
    depends_on:
      - crudtestDb
    environment:
      - DB_HOST=crudtest-db
      - DB_NAME=db_crudtest
      - DB_SA_PASSWORD=password@1234#
    networks:
      - frontend


volumes:
  sql_data: