version: '3.4'

networks:
  frontend:
  elastic:
    driver: bridge

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    container_name: es01
    restart: always
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - IPC_LOCK
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  crudtestDb:
    container_name: crudtest-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@1234#
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - frontend

  kib01:
    image: docker.elastic.co/kibana/kibana:7.9.0
    restart: always
    container_name: kib01
    ports:
      - 5601:5601
    depends_on:
      - es01
    environment:
      ELASTICSEARCH_URL: http://localhost:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    volumes:
      - kibana-data:/usr/share/kibana/data
    networks:
      - elastic

  mc2.crudtest.presentation.server:
    image: ${DOCKER_REGISTRY-}mc2crudtestpresentationserver
    build:
      context: .
      dockerfile: Mc2.CrudTest.Presentation/Server/Dockerfile
    ports:
        - 9080:8080
    depends_on:
      - crudtestDb
    environment:
      - DB_HOST=crudtest-db
      - DB_NAME=db_crudtest
      - DB_SA_PASSWORD=password@1234#
    networks:
      - frontend
      - elastic

volumes:
  sql_data:
  data01:
    driver: local
  kibana-data:
    driver: local